spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update

springdoc:
  swagger-ui:
    url: /openapi.yaml

jwt_secret: secret
subject: User details
issuer: my-spring-boot-rest
claim: username